#!/bin/bash

set -e

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

files=$( (git diff --cached --name-only --diff-filter=ACMR | grep -Ei "\.java$") || true)

if [ -n "${files}" ]; then
#    comma_files=$(echo "$files" | paste -s -d "," -)
    "${REPO_ROOT_DIR}/gradlew" googleJavaFormat  &>/dev/null
    git add "$(echo "$files" | paste -s -d " " -)"
fi
