#!/bin/bash

set -e

REPO_ROOT_DIR=$(git rev-parse --show-toplevel)

files=$( (git diff --cached --name-only --diff-filter=ACMR | grep -Ei "\.java$") || true)

if [ -n "$files" ]; then
    "$REPO_ROOT_DIR/gradlew" compile  &>/dev/null
    git add $(echo "$files" | paste -s -d " ")
fi
